### ISSUE TITLE
Demos are broken.

### ISSUE THREAD

**Issue by amio** [react-component/editor-mention#11]
http://react-component.github.io/editor-mention/examples/mentionMode.html
![image](https://user-images.githubusercontent.com/215282/29455155-b2f42eec-83d5-11e7-84bd-5b084d960ecb.png)

And screenshot missing: http://react-component.github.io/editor-mention/
![image](https://user-images.githubusercontent.com/215282/29455138-a10783aa-83d5-11e7-8ce3-8b31610a358f.png)

**Comment by yesmeck** [comment]
没看懂，哪里坏了？

**Comment by amio** [comment]
哦，先前理解错了，以为是标签组件，以逗号分隔输入 “movie, drama” 的那种标签。刚又试了下发现其实是 @ 输入。

另一个缺失截图的问题还是在。
![image](https://user-images.githubusercontent.com/215282/32483896-d693f33a-c3d8-11e7-9f8d-069723d95f52.png)
