### ISSUE TITLE
支持ie8吗？

### ISSUE THREAD

**Issue by guxingke201** [react-component/editor-mention#22]
import babel-polyfill后，在IE8下报异常
`'this._defaultValues' 为空或不是对象`
![image](https://user-images.githubusercontent.com/8326941/32825288-662f8918-ca1f-11e7-85d4-d7c6797e941d.png)

**Comment by RaoHai** [comment]
浏览器支持跟 draft-js 的一致，IE 的支持是 IE11 和 Edge。不好意思。我会修改 README 的。
