### ISSUE TITLE
Immutable peerDep causing issues

### ISSUE THREAD

**Issue by megawac** [react-component/editor-mention#26]
The peerDep in the package.json is causing issues for my project. We need to use `immutable~3.8` due to some of the features in that version but editor mention requires `immutable~3.7`. Because its refrenced as a peer dependency and I can't install 3.7.4 I get issues building the shrinkwrap for my project despite not using `editor-mention` (it's being included through ant).

I haven't looked at the compatibility for this project but can you not use `immutable^3.7` or directly depend on 3.7 so it doesn't conflict with project installs of immutable?

**Comment by Tymek** [comment]
Should `immutable` be `peerDependency`?
This seems like an ordinary dependency to me: https://github.com/react-component/editor-mention/blob/3a566add7abdeffefa099b6650d0ab1e67f930f3/src/model/mentionStore.js#L2
