### ISSUE TITLE
需要添加 getSuggestionContainer 默认值

### ISSUE THREAD

**Issue by fiture** [react-component/editor-mention#4]
ant.design `Mention` 组件没有如果没传 `getSuggestionContainer` 属性进来，会导致下面的代码报错：

https://github.com/react-component/editor-mention/blob/master/src/Mention.jsx#L117

@RaoHai 麻烦帮忙看下

**Comment by yesmeck** [comment]
https://github.com/react-component/editor-mention/blob/9ab03acabc5575d81b12b40e2151ff2962d405a0/src/component/Mention.react.jsx#L165

已经有判断了。
