### ISSUE TITLE
github版本和npm版本不一致

### ISSUE THREAD

**Issue by nekronhuang** [react-component/editor-mention#6]
npm版本已经改成了0.6.9，而仓库版本是0.6.0。。。

然后。。。

为何0.6.9(还是之前的哪个版本)把value和onChange的回调值从`editorState`改成了`contentState`。。。

然后。。。

antd的mention component少ref，我没法一直往下拿到最下层draft的Editor，需要使用他的focus功能

**Comment by yesmeck** [comment]
antd 已提供 focus 方法。https://github.com/ant-design/ant-design/blob/b740d86bbff14b9c2486cf9f36457252f5946d00/components/mention/index.tsx#L113
